project:
  type: book
  output-dir: docs

book:
  title: "Chiral_Phonons"
  author: "DB; JEB; FFGL"
  date: "3/12/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    - cadena.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
 



